#!/usr/bin/env zsh

ztput() {
  reset() {
    printf "%s""\e[0m"
  }
  bold() {
    printf "%s""\e[1m"
  }
  dim() {
    printf "%s""\e[2m"
  }
  cvwoah=11
  cvvis() {
    printf "%s""\033[?25h"
  }
  civis() {
    printf "%s""\033[?25l"
  }
  case $1 in
    (reset) reset && return 0 ;;
     (bold)  bold && return 0 ;;
      (dim)   dim && return 0 ;;
    (cvvis) cvvis && return 0 ;;
    (civis) civis && return 0 ;;
  esac
  colour_code=${1[1]}
  ([ "$colour_code" = "setaf" ] || [ "$colour_code" = "setab" ]) && {
    colour_code=${2[1]}
  }
  (( colour_code < 0 || colour_code > 255 )) && {
    [ "$LIBMISCDEBUG" = 1 ] && {
      noglob printf "%s""$colour_code"
    }
    return 0
  } || {
    printf "%s""\e[3${colour_code}m"
  }
}

ctext() {
  # set text colour (d prefix = background)
  case $1 in
    (black) ztput 0 ;;
      (red) ztput 1 ;;
    (green) ztput 2 ;;
   (yellow) ztput 3 ;;
     (blue) ztput 4 ;;
  (magenta) ztput 5 ;;
     (cyan) ztput 6 ;;
    (white) ztput 7 ;;
   (dblack) ztput setab 0 ;;
     (dred) ztput setab 1 ;;
   (dgreen) ztput setab 2 ;;
  (dyellow) ztput setab 3 ;;
    (dblue) ztput setab 4 ;;
 (dmagenta) ztput setab 5 ;;
    (dcyan) ztput setab 6 ;;
   (dwhite) ztput setab 7 ;;
    (reset) ztput reset ;; # reset to default colours
  esac
  case $2 in
          (std) echo "${@:3}" && ztput reset ;; # print with newline
          (nnl) echo -n "${@:3}" && ztput reset ;; # print without newline
     (std,bold) ztput bold && echo "${@:3}" && ztput reset ;; # print bold, with newline
     (nnl,bold) ztput bold && echo -n "${@:3}" && ztput reset ;; # print bold, without newline
      (std,dim) ztput dim && echo "${@:3}" && ztput reset ;; # print dim, with newline
      (nnl,dim) ztput dim && echo -n "${@:3}" && ztput reset ;; # print dim, without newline
     (std,nres) echo "${@:3}" ;; # print with newline, do not reset afterwards
     (nnl,nres) echo -n "${@:3}" ;; # print without newline, do not reset afterwards
(std,bold,nres) ztput bold && echo "${@:3}" ;; # print bold, with newline, no reset afterwards
(nnl,bold,nres) ztput bold && echo -n "${@:3}" ;; # print bold, without newline, no reset afterwards
 (std,dim,nres) ztput dim && echo "${@:3}" ;; # print dim, with newline, no reset afterwards
 (nnl,dim,nres) ztput dim && echo -n "${@:3}" ;; # print dim, without newline, no reset afterwards
  esac
  # return 0
  return 0
}
