#!/usr/bin/env zsh

ztput() {
  reset() {
    printf "%s""\e[0m"
  }
  bold() {
    printf "%s""\e[1m"
  }
  dim() {
    printf "%s""\e[2m"
  }
  cvwoah=11
  cvvis() {
    printf "%s""\033[?25h"
  }
  civis() {
    printf "%s""\033[?25l"
  }
  case $1 in
    (reset) reset && return 0 ;;
     (bold)  bold && return 0 ;;
      (dim)   dim && return 0 ;;
    (cvvis) cvvis && return 0 ;;
    (civis) civis && return 0 ;;
  esac
  colour_code=${1[1]}
  ([ "$colour_code" = "setaf" ] || [ "$colour_code" = "setab" ]) && {
    colour_code=${2[1]}
  }
  (( colour_code < 0 || colour_code > 255 )) && {
    [ "$LIBMISCDEBUG" = 1 ] && {
      noglob printf "%s""$colour_code"
    }
    return 0
  } || {
    printf "%s""\e[3${colour_code}m"
  }
}

ctext() {
  # set text colour
  [ "$1" = black ] && {
    ztput 0
  }
  [ "$1" = red ] && {
    ztput 1
  }
  [ "$1" = green ] && {
    ztput 2
  }
  [ "$1" = yellow ] && {
    ztput 3
  }
  [ "$1" = blue ] && {
    ztput 4
  }
  [ "$1" = magenta ] && {
    ztput 5
  }
  [ "$1" = cyan ] && {
    ztput 6
  }
  [ "$1" = white ] && {
    ztput 7
  }
  # set background colour
  [ "$1" = dblack ] && {
    ztput setab 0
  }
  [ "$1" = dred ] && {
    ztput setab 1
  }
  [ "$1" = dgreen ] && {
    ztput setab 2
  }
  [ "$1" = dyellow ] && {
    ztput setab 3
  }
  [ "$1" = dblue ] && {
    ztput setab 4
  }
  [ "$1" = dmagenta ] && {
    ztput setab 5
  }
  [ "$1" = dcyan ] && {
    ztput setab 6
  }
  [ "$1" = dwhite ] && {
    ztput setab 7
  }
  # reset to default colours
  [ "$1" = reset ] && {
    ztput reset
  }
  # print with newline
  [ "$2" = std ] && {
    echo "${@:3}"
    ztput reset
  }
  # print without newline
  [ "$2" = nnl ] && {
    echo -n "${@:3}"
    ztput reset
  }
  # print bold, with newline
  [ "$2" = std,bold ] && {
    ztput bold
    echo "${@:3}"
    ztput reset
  }
  # print bold, without newline
  [ "$2" = nnl,bold ] && {
    ztput bold
    echo -n "${@:3}"
    ztput reset
  }
  # print dim, with newline
  [ "$2" = std,dim ] && {
    ztput dim
    echo "${@:3}"
    ztput reset
  }
  # print dim, without newline
  [ "$2" = nnl,dim ] && {
    ztput dim
    echo -n "${@:3}"
    ztput reset
  }
  # print with newline, do not reset colours after print
  [ "$2" = std,nres ] && {
    echo "${@:3}"
  }
  # print without newline, do not reset colours after print
  [ "$2" = nnl,nres ] && {
    echo -n "${@:3}"
  }
  # print bold, with newline, do not reset colours after print
  [ "$2" = std,bold,nres ] && {
    ztput bold
    echo "${@:3}"
  }
  # print bold, without newline, do not reset colours after print
  [ "$2" = nnl,bold,nres ] && {
    ztput bold
    echo -n "${@:3}"
  }
  # print dim, with newline, do not reset colours after print
  [ "$2" = std,dim,nres ] && {
    ztput dim
    echo "${@:3}"
  }
  # print dim, without newline, do not reset colours after print
  [ "$2" = nnl,dim,nres ] && {
    ztput dim
    echo -n "${@:3}"
  }
  # extras (symbols, emojis)
  [ "$2" = chkmrk ] && {
    ztput bold
    echo -e "\xE2\x9C\x94"
    ztput reset
  }
  [ "$2" = xmrk ] && {
    ztput bold
    echo "X"
    ztput reset
  }
  [ "$2" = grin ] && {
    ztput bold
    echo "😀"
    ztput reset
  }
  [ "$2" = smile ] && {
    ztput bold
    echo "☺"
    ztput reset
  }
  [ "$2" = glss ] && {
    ztput bold
    echo "😎"
    ztput reset
  }
  [ "$2" = frown ] && {
    ztput bold
    echo "☹"
    ztput reset
  }
  [ "$2" = horrif ] && {
    ztput bold
    echo "😱"
    ztput reset
  }
  [ "$2" = dead ] && {
    ztput bold
    echo "☠"
    ztput reset
  }
  # return 0
  return 0
}
